### ISSUE TITLE
Extract metadata from one XML file

### ISSUE THREAD

**Issue by ajhoekst** [Dance-Data-Project/smith-capstone-23#2]
Use the "XML" R package to extract the fields below.

- [ ] Return timestamp: Return -> ReturnHeader -> ReturnTs
- [ ] Filer's EIN: Return -> ReturnHeader -> Filer -> EIN
- [ ] Return type code: Return -> ReturnHeader -> ReturnTypeCd
- [ ] Fiscal year start date: Return -> ReturnHeader -> TaxPeriodBeginDt
- [ ] Fiscal year end date: Return -> ReturnHeader -> TaxPEriodEndDt

**Comment by raevard** [comment]
Completed with task 3
