### ISSUE TITLE
Create metadata table

### ISSUE THREAD

**Issue by ajhoekst** [Dance-Data-Project/smith-capstone-23#3]
First complete #2 

Iterate through all filings, compiling the metadata from #2 into a table/dataframe. Answer the questions below.

1. How many filings do we have each year?
2. How many companies (EINs) do we have each year?
3. Which companies had more than one filing in a year?
4. Are there years for which there is a "gap year" between filings for a company?

**Comment by ajhoekst** [comment]
@q-w-a Looks like you got a good portion of this done already!

Once you think this is done, try creating a pull request for the branch so we can merge it into main. This will help the team review your contribution.

**Comment by q-w-a** [comment]
For questions 1-3, are we thinking of the year as the year of the return timestamp or the year of the fiscal year start date?

**Comment by ajhoekst** [comment]
Great question! When we analyze fiscal year 2020 (FY20) for companies...we are referring to the filing with a tax period _ending_ in 2020.
